name: 'Radix environment helper'
description: 'Handles per-environment setup for OMNIA Radix'
inputs:
  name:
    description: 'Name of your feature environment (e.g ab-12345)'
    required: true
  app:
    description: 'Name of your application (in radix)' # TODO: Extract from radixconfig
    required: false
  action:
    description: 'Action to perform (can be one of create | teardown | update-secrets | clear-orphans | check-environment)'
    required: false
  vault:
    description: 'Name of the keyvault you want to fetch secrets from (required if action = update-secrets)'
    required: false
  branch:
    description: 'Name of branch to build from'
    required: false
  registry:
    description: 'Name of the container registry (required to perform teardown)'
    required: false
  context:
    description: 'Location of helper files (secret-map.json, variables.json etc'
    required: false
    default: ./
  debug:
    description: 'Print out additional information'
    required: false
outputs:
  exists: # id of output
    description: 'Prints if check-environment is ran. Returns true or false'
runs:
  using: 'node20'
  main: 'dist/index.js'
